// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/5/2025, 9:06:10 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/plugins/**/*.{js,ts,mjs}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/composables/**/*.{js,ts,mjs}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/utils/**/*.{js,ts,mjs}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ngatyebrianoko/Documents/Design Projects/Explorimentalist/GPT_apps/epàlwi-rèbbo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;